name: Build BillPayment Project

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 17 with Maven cache
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Build and run tests
      - name: Build with Maven
        run: mvn clean package --batch-mode

      # Step 4: Upload all JAR artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: billpayment-jars
          path: |
            **/target/*.jar
            !**/original-*.jar

